### ISSUE TITLE
🐛 Bug Report:  type '_Map<String, dynamic>' is not a subtype of type 'List<dynamic>' 

### ISSUE THREAD

**Issue by obiwanzenobi** [appwrite/sdk-for-dart#41] opened 2023-06-08 12:53 UTC
### 👟 Reproduction steps

While creating collection, some combination of permissions causes server to respond with a wrong type for "permissions" which leads to SDK crash.  
https://github.com/appwrite/sdk-for-dart/blob/master/lib/src/models/collection.dart#L12 and https://github.com/appwrite/sdk-for-dart/blob/master/lib/src/models/collection.dart#L44

Wrong response: 
`{"$id":"category","$createdAt":"2023-06-08T12:45:14.832+00:00","$updatedAt":"2023-06-08T12:45:14.832+00:00","$permissions":{"0":`

![Screenshot 2023-06-08 at 14 40 54](https://github.com/appwrite/sdk-for-dart/assets/5386385/7f4103a3-8c96-4139-a911-efec70cc0c6e)

### 👍 Expected behavior

SDK should handle both response types array and object OR server should be consistent with a response structure.

### 👎 Actual Behavior

SDK handles response only while permissions field is an array.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Local selfohosted appwrite 1.3.4

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment] 2023-06-08 14:21
@obiwanzenobi thanks for raising this! 🙏🏼 This actually looks like a duplicate of https://github.com/appwrite/appwrite/issues/5661 so I'm going to close this. Please 👍🏼 the related issue.

**Closed by stnguyen90** 2023-06-08 14:21 UTC
Labels: bug
